Apuls = ["Sonny Rollins",
    "Franco",
    "New York Dolls",
    "Al Green",
    "Bob Dylan",
    "Charlie Parker",
    "Firesign Theatre",
    "Lefty Frizzell",
    "Neil Young",
    "Sly & the Family Stone",
    "Thelonious Monk"
]

A = ["Aretha Franklin",
    "Angry Samoans",
    "Bonnie Raitt",
    "David Bowie",
    "Amy Rigby",
    "Andy Fairweather Low",
    "Archers of Loaf",
    "Azealia Banks",
    "B-52's",
    "Bettye Lavette",
    "Bill Withers",
    "Bing Crosby",
    "Black Uhuru",
    "Blind Willie Johnson",
    "Bob Dylan",
    "Bob Marley & the Wailers",
    "Brad Paisley",
    "Bruce Springsteen",
    "Burial",
    "Captain Beefheart and the Magic Band",
    "Charlie Parker",
    "Chic",
    "Cornershop",
    "Creedence Clearwater Revival",
    "Dawn Oberg",
    "De La Soul",
    "Delaney & Bonnie",
    "Dionne Warwick",
]

Aminus = ["Al Green",
    "Ani DiFranco",
    "Amadou & Mariam",
    "Amy Rigby",
    "Archers of Loaf",
    "A Place to Bury Strangers",
    "Aaron Neville",
    "ABC",
    "Aerosmith",
    "Aesop Rock",
    "Allo Darlin'",
    "Arto Lindsay",
    "Atmosphere",
    "A Flock of Seagulls",
    "Abdullah Ibrahim",
    "Ab-Soul",
    "Aesop Rock & Homeboy Sandman",
    "Alanis Morissette",
    "Alex Chilton",
    "Ali Farka Tour����",
    "Ali Hussan Kuban",
    "Alicia Keys",
    "Amy Allison",
    "Amy LaVere",
    "Ann Peebles",
    "Arca",
    "Arcade Fire",
    "Aretha Franklin",
    "Art Brut",
    "Ashford & Simpson",
    "Asleep at the Wheel",
    "Ass Ponys",
    "Astor Piazzolla",
    "Asylum Street Spankers",
]

Bplus = ["Aretha Franklin",
    "Al Green",
    "B.B. King",
    "Aerosmith",
    "Albert Collins",
    "Alex Chilton",
    "Bachman-Turner Overdrive",
    "Barrence Whitfield and the Savages",
    "D Train",
    "10cc",
    "Action Bronson",
    "Albert Griffiths and the Gladiators",
    "Angry Samoans",
    "Anne Murray",
    "Archie Shepp",
    "Arlo Guthrie",
    "Ashford & Simpson",
    "Atmosphere",
    "Aztec Camera",
    "B-52's",
    "Bad Brains",
    "Beck",
    "Bee Gees",
]

B = ["Aretha Franklin",
    "B.B. King",
    "Alice Cooper",
    "Anne Murray",
    "Arlo Guthrie",
    "Al Green",
    "10,000 Maniacs",
    "Aerosmith",
    "Alan Price",
    "Ann Peebles",
    "Asleep at the Wheel",
    "Augie Meyers",
    "Bad Company",
    "Barry White",
    "10cc",
    "AC/DC",
    "Afrika Bambaataa and Family",
    "Allen Toussaint",
    "Alpha Blondy",
    "Amazing Rhythm Aces",
    "Angst",
    "Art of Noise",
    "Ashford & Simpson",
    "Bachman-Turner Overdrive",
    "Bad Religion",
    "Badfinger",
    "Bananarama",
    "Bee Gees",
    "Big Daddy Kane",
]

C = ["Barry Manilow",
    "Bette Midler",
    "Abba",
    "AC/DC",
    "Alice Cooper",
    "Barry White",
    "Bay City Rollers",
    "Bill Withers",
    "Billy Idol",
    "Billy Joel",
    "38 Special",
    "Aerosmith",
    "Andrew Gold",
    "Andy Pratt",
    "Anne Murray",
    "Aretha Franklin",
    "Arrested Development",
    "Ashford & Simpson",
    "Average White Band",
    "B.J. Thomas",
    "Barbara Mandrell",
    "Barbra Streisand",
    "Bee Gees",
]

D=["Debby Boone",
"Enya",
"John Denver",
]

E=
